# Generated by Django 5.1.4 on 2025-01-07 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_categories_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
