# Generated by Django 5.1.4 on 2025-02-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='users_images', verbose_name='Аватар'),
        ),
    ]
