# Generated by Django 5.1.4 on 2025-02-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_comment_user_full_name_comment_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
