# Generated by Django 5.1.4 on 2025-03-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_alter_review_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('created',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
